### ISSUE TITLE
support sequence of mappings with multiple keys

### ISSUE THREAD

**Issue by microtodd** [microtodd/yamledit#5]
Like this:

```
sequence:
    - Foo: var
      Foo2: var2
      Foo3: var3
```
